version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:10.0.1.29"
networks:
  default:
    external:
      name: kafka_default